[project]
name = "logvar-diffusion"
version = "1.0.0"
description = "A small project for a different diffusion model"
readme = "README.md"
dependencies = [
    "torch>=2.7",
    "setuptools",
    "einops",
    "matplotlib",
    "numpy",
    "click",
    "tqdm",
]
